// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fb_haploid
DataFrame fb_haploid(NumericVector snp_locations, NumericVector p0, NumericVector p1, double p_assign, double scale);
RcppExport SEXP HMMancestry_fb_haploid(SEXP snp_locationsSEXP, SEXP p0SEXP, SEXP p1SEXP, SEXP p_assignSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type snp_locations(snp_locationsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type p_assign(p_assignSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    __result = Rcpp::wrap(fb_haploid(snp_locations, p0, p1, p_assign, scale));
    return __result;
END_RCPP
}
// fb_diploid
DataFrame fb_diploid(NumericVector snp_locations, NumericVector p0, NumericVector p1, double p_assign, double scale);
RcppExport SEXP HMMancestry_fb_diploid(SEXP snp_locationsSEXP, SEXP p0SEXP, SEXP p1SEXP, SEXP p_assignSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type snp_locations(snp_locationsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type p_assign(p_assignSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    __result = Rcpp::wrap(fb_diploid(snp_locations, p0, p1, p_assign, scale));
    return __result;
END_RCPP
}
