# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Inferring hidden ancestry states from haploids
#'
#' @description stuff goes here
#'@export
c_est_fwd_back <- function(snp_locations, k0, k1, p_assign, p_trans) {
    .Call('HMMancestry_c_est_fwd_back', PACKAGE = 'HMMancestry', snp_locations, k0, k1, p_assign, p_trans)
}

#'@export
c_est_fwd_back_diploid <- function(snp_locations, k0, k1, p_assign, p_trans) {
    .Call('HMMancestry_c_est_fwd_back_diploid', PACKAGE = 'HMMancestry', snp_locations, k0, k1, p_assign, p_trans)
}

#'@export
lapply1 <- function(input, f) {
    .Call('HMMancestry_lapply1', PACKAGE = 'HMMancestry', input, f)
}

