# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
c_est_fwd_back <- function(snp_locations, k0, k1, p_assign, p_trans) {
    .Call('hmmspore_c_est_fwd_back', PACKAGE = 'hmmspore', snp_locations, k0, k1, p_assign, p_trans)
}

#'@export
lapply1 <- function(input, f) {
    .Call('hmmspore_lapply1', PACKAGE = 'hmmspore', input, f)
}

